```{r}
#| label: setup
#| include: false
#| warning: false
#| echo: false

source("_common.R")
```

# Theorie

Im Folgenden werden zuerst Grundlagen gebende theoretische Aspekte mit dem aktuellen Forschungsstand angereichert. Zu Beginn wird auf geschlechtergerechte Sprache eingegangen. Dabei wird die aktuelle wissenschaftliche Debatte kritisch beleuchtet und die Kernpunkte des Diskurses hervorgehoben. Auch die empirische Seite der Forschung kommt zum Tragen, wie auch die (gesellschaftliche) Ablehnung geschlechtergerechter Sprache und die Gründe für das Ausmaß der Polarisierung. Im zweiten Teil werden Bundestagsanträge und ihre Rolle in Politics thematisiert. Es wird gezeigt, welchen Zweck Anträge im parlamentarischen Alltag erfüllen, welche Fraktionen Anträge als Instrument vermehrt nutzen und wie die Fraktionen sich in der Abstimmung zu Anträgen verhalten. Auch wird beleuchtet, inwiefern Anträge in und für die Forschung eine Rolle spielen. Im dritten Teil steht der aktuelle Forschungsstand zum Thema Populismus im Fokus. Dabei wird an die aktuelle wissenschaftliche Diskussion angeknüpft und verschiedene Definitionen vorgestellt. Auch verschiedene wissenschaftliche Herangehensweisen zur Arbeit mit dem Konzept Populismus werden kurz vorgestellt. Zuletzt geht es um Populismus und Social Media.

Im Anschluss daran wird theoretisch und wissenschaftlich fundiert argumentiert, ... (Blick auf Theorien werfen)

## Geschlechtergerechte Sprache {#sec-ges-theorie}

Über Sinn und Zweck geschlechtergerechter Sprache, auch "Gendern" genannt, gibt es eine kontroverse wissenschaftliche Auseinandersetzung [vgl. @hackmann2023: 11], bei der die Wirkmächtigkeit der Sprache vermutlich von beiden Seiten – Gegner\*innen wie auch Befürworter\*innen – überschätzt wird [vgl. @lind2022: 36]. Noch viel kontroverser ist die gesellschaftliche Debatte darüber. Fest steht: Bei geschlechtergerechter Sprache handelt es sich nicht um ein Randgruppenphänomen [vgl. @weidner2021: 287] und ebenso wenig um eine reine "Akademikersprache", denn geschlechtergerechte Sprache wird als "TIN\*-klusive"[^01-theorieteil-1] Sprache von Betroffenen unabhängig von deren Bildungsgrad oder sozialen Schicht genutzt [vgl. @schütze2023: 156-158].

[^01-theorieteil-1]: TIN\* steht für Trans-\*, Inter\*- und Nicht-binäre-Menschen.

Geschlechtergerechte Sprache wird hierbei als der Versuch verstanden, Geschlechtergerechtigkeit in der Sprache herzustellen, wobei ein wesentlicher Bestandteil geschlechtergerechter Sprache die Sichtbarmachung von in der Sprache nicht abgebildeten Geschlechtern ist [vgl. @rödder2022: 6]. Sprache ist ein "Machtkonstrukt" [@rödder2022: 6], das auf die Wirklichkeit der Rezipient\*innen – und damit von uns allen – einwirkt. Es gibt keine einheitliche Art des Genderns [vgl. @müller-spitzer2020: 55], trotzdem seien an dieser Stelle exemplarisch einige verbreitete Formen geschlechtergerechter Sprache genannt: das Binnen-I (StudentInnen), die Beidnennung (Studentinnen und Studenten), die Substantivierung von Präsenspartizipien (Studierende) sowie Zeichensetzungen innerhalb von Wörtern, angefangen beim Gender-Gap (Student_innen) über den Gender-Stern (Student\*innen) zum Doppelpunkt (Student:innen) [vgl. @kotthoff2022: 12]. Zuletzt gehört auch das von der feministischen Linguistin Luise F. Pusch bevorzugte generische Femininum sowie das generische Maskulinum zu Formen geschlechtergerechter Sprache [vgl. @wizorek2022: 4; vgl. @eisenberg2022: 35], das einen der zentralen Punkte der Debatte darstellt.

Schon seit den 1970er Jahren wird das generische Maskulinum von der feministischen Linguistik (auch: Gender-Linguistik) kritisiert [vgl. @müller-spitzer2020: 53], da es den Mann als Norm festsetzt [vgl. @günthner2017: 3]. Aus historischer Sicht ist festzuhalten, dass das generische Maskulinum bei weitem nicht schon seit Jahrhunderten verwendet wird, wie teils in der Debatte behauptet [vgl. @weidner2021: 282; @müller-spitzer2021: 2], und dass die Entwicklung dich deutlich von der ausschließlichen Verwendung des generischen Maskulinums entfernt, ist angesichts von etablierten femininen Formen wie Bundeskanzlerin oder Ärztin offensichtlich [vgl. @müller-spitzer2022: 39]. Im Mittelpunkt steht bei diesem Streitpunkt die Frage, ob das Genus unabhängig vom Sexus ist, also das grammatikalische Geschlecht unabhängig vom biologischen Geschlecht – wobei in der Forschung eigentlich weitgehende Klarheit über die Unabhängigkeit beider Aspekte herrscht. Allerdings argumentiert die Gender-Linguistik, dass die Korrelation von Genus und Sexus stark ist [vgl. @schütze2023: 143; @lobin2019: 1], denn: Das generische Maskulinum wird zwar von den Schreibenden generisch gemeint, die Interpretation der Lesenden erfolgt dann aber oft spezifisch [siehe dazu auch: @diewald2022: 16]. Kritiker\*innen bezeichnen diesen Standpunkt jedoch als "reine Polemik" [@eisenberg2022: 35]. Das grundsätzliche Problem, dass nicht immer eindeutig ist, ob maskuline Formen gerade generisch oder spezifisch sind, besteht allerdings [vgl. @günthner2017: 4; @schütze2023: 144] – auch wenn dies teils bestritten wird [vgl. @payr2021: 23-36].

Doch was sagt die empirische Forschung dazu? Zahlreiche psycholinguistische Experimente haben seit Anfang der 2000er nachgewiesen, dass "wirklichkeitskonstituierende Auswirkungen" [@lind2022: 36] von Sprache hinsichtlich der Geschlechtsvorstellung existieren, beim generischen Maskulinum in der Vorstellung also mehr an Männer\* als an Frauen\* gedacht wird [vgl. @lind2022: 40, 41; @müller-spitzer2018: o. S.; @kotthoff2022: 12; @günthner2017: 4; @schütze2023: 148; @diewald2022: 3, 11].[^01-theorieteil-2] Allerdings wird an diesen Studien kritisiert, dass beim Studiendesign wichtige Faktoren außer Acht gelassen wurden und fehlende sprachwissenschaftliche Expertise die Ergebnisse unbrauchbar macht [vgl. @payr2021: 30, 31].[^01-theorieteil-3] Zudem gibt es jüngere Studien, die gegenteilige Resultate aufzeigen [vgl. @payr2021: 30]. Bei dieser unklaren empirischen Lage, die sich aus dem sehr gespaltenen Bild der Forschung ergibt, scheint eine möglichst objektive Prüfung der vorhandenen Studien äußerst sinnvoll. Am Ende eines solchen Prozesses könnte entweder mehr Klarheit vorhanden sein oder alternativ diese über neue Forschung geschaffen werden.

[^01-theorieteil-2]: Einen (relativ alten) Überblick über die betreffenden Studien gibt es bei @braun2005.

[^01-theorieteil-3]: Diese Kritik ist grundsätzlich durchaus ernst zu nehmen, jedoch muss darauf hingewiesen werden, dass auch sie wiederum Kritik hervorgerufen hat. Beispielsweise bemängelt Fabian Payr fehlende Repräsentativität der Experimente [-@payr2021: 28], obwohl es bei Experimenten grundsätzlich gar nicht üblich ist, Repräsentativität zu beanspruchen. Dass Messergebnisse trotzdem generalisierbar sind, "wenn der zu untersuchende Sachverhalt unabhängig von der jeweiligen Teilgruppe existiert, an der er untersucht wird" [@brosius2022: 244], ist allerdings unstrittig. Auch Miriam Lind und Damaris Nübling [-@lind2022: 41] bemängeln Payrs fehlende empirische Expertise.

Trotz der hehren Ziele der Befürworter\*innen von geschlechtergerechter Sprache gibt es auch berechtigte Kritik an geschlechtergerechter Sprache. So darf "Inklusion \[...\] nicht Exklusion bewirken" [@weidner2021: 286]: Menschen mit Migrationshintergrund und wenig Bildung haben erhebliche Probleme bei einer komplexeren Sprache [vgl. @weidner2021: 285-286; @payr2021: 103]. Auch ein falscher politischer Fokus wird geschlechtergerechter Sprache attestiert, weil ihr Beitrag zu echter Gleichberechtigung zu gering ist [vgl. @weidner2021: 288], in dem sie die Fronten unnötig verhärtet [vgl. @weidner2021: 281; siehe auch @mau2024] und politisches Kapital verspielt.

Ablehnung gegen geschlechtergerechte Sprache gibt es nicht nur in der Wissenschaft. "Vor allem von konservativer und rechter Seite wird der Gender-Begriff \[...\] mit Zerrbildern und Lügen aufgeladen und damit von seiner tatsächlichen Bedeutung entfernt" [@wizorek2022: 4]. Die Debatte in der Öffentlichkeit ist schon seit Jahren polarisiert [vgl. @lobin2018]. Dabei wird das Thema als eine Art Kulturkampf wahrgenommen [vgl. @wizorek2022: 5], was der sich in Form von "tendenziöser Berichterstattung" auch in den Medien widerspiegelt [vgl. @lobin2019: o. S.]. Konstruktivität ist selten zu finden [vgl. @weidner2021: 280], was angesichts der moralisierten Debatte [siehe dazu @stefanowitsch2018; vgl. @payr2021: 115-124; @weidner2021: 284] wenig überrascht. Moralisierte Totschlagargumente wie "der privilegierte alte weiße Mann", der nicht befähigt sei, sich unvoreingenommen und neutral zum Thema zu äußern, auf der einen und "Sprachdiktatur" oder "Gendergaga" auf der anderen Seite machen eine konstruktive Diskussion geradezu unmöglich [vgl. @weidner2021: 287]. Letzteres soll den Befürworter\*innen jegliche Rationalität absprechen und setzt die Gefahr einer Aufoktroyierung der Sprache ins Verhältnis zur NS- oder DDR-Diktatur. Dieser Vergleich ist, wie noch zu sehen sein wird, absurd und übertritt die Grenzen eines sachlichen Dialogs vollständig [vgl. auch @weidner2021: 283].\
Erstaunlich ist, dass die Polemik der öffentlichen Debatte auch in die wissenschaftliche übergeschwappt scheint. Statt über die tatsächlichen Argumente zu streiten, werden Studienergebnisse konsequent ignoriert, wissenschaftliche Gegenpositionen unerwähnt gelassen [vgl. @simon2022: 19], und unreflektiert der Gegenseite eine ideologische Motivation vorgeworfen [vgl. @schütze2023: 160].[^01-theorieteil-4] Kein Wunder, dass sich Wissenschaftler\*innen nach der Rückkehr zum sachlichen Diskurs sehnen [vgl. @weidner2021: 288; @müller-spitzer2020: 55; @müller-spitzer2021: 10; @müller-spitzer2022: 42].

[^01-theorieteil-4]: Als Beispiel sei explizit auf die Monographie von Fabian Payr hingewiesen [-@payr2021], dessen guten Argumente in der Polemik des ganzen Werkes fast vollständig untergehen. Das Versprechen der "sachlichen Kritik" hält das Buch keinesfalls. Aber auch renommierte Linguist\*innen wie Peter Eisenberg [-@eisenberg2022: 35] vergreifen sich regelmäßig im Ton. Eine gute und konstruktive wissenschaftliche Debatte sieht anders aus.

Horst Simon identifiziert zwei zentrale Gründe für diese starke Polarisierung [-@simon2022: 21]: Sprache ist enorm identitätsgeladen und Menschen haben eine innige Verbundenheit mit ihrer individuellen Sprachausprägung. Das führt zur Ablehnung von allem, "was durch Variation und Wandel die subjektive Essenzialität ihrer Sprache infrage stellt" [@simon2022: 21; vgl. auch @wizorek2022: 5]. Demnach handelt es sich weniger um einen "Sprachkampf" als einen "Kulturkampf" [@simon2022: 22]. Miriam Lind und Damaris Nübling vermuten zudem, dass die Debatte um geschlechtergerechte Sprache als Vorwand genutzt wird, um misogyne und queerfeindliche Ansichten zu artikulieren [vgl. @lind2022: 38].

Die Gefahr eines "Sprachzwangs", die von etlichen Kritiker\*innen geschlechtergerechter Sprache eingebracht wird, ist allerdings übertrieben. Zwar gibt es beispielsweise an der Universität Kassel einen Fall, dass die Verwendung des generischen Maskulinums durch einen Studenten einen Punktabzug zur Folge hatte [vgl. Lohr 2021 zit. n. @weidner2021: 281], der Zwang wird aber von der Seite der Kritiker\*innen viel stärker ausgeübt. So gibt es mittlerweile Verbote bestimmter Formen geschlechtergerechter Sprache in Bayern, Sachsen, Sachsen-Anhalt, Schleswig-Holstein und Hessen [vgl. @jerabek2024: o. S.; @mdrsachsen2023: o. S.; @zeitonline2023: o. S.; @schomburg2023: o. S.; @peters2024: o. S.].

Interessant ist auch die Perspektive anderer Länder. Im Englischen funktioniert geschlechtergerechte Sprache beispielsweise ganz anders, die deutsche Herangehensweise wirkt für englische Feminist\*innen "sexistisch, antiquiert und kein bisschen inklusiv" [@pollatschek2022: 8]. Das englische Konzept lautet dabei: Nur (sprachliche) Gleichheit führt auch zu Gleichheit. Nele Pollatschek spricht von einer Generisch-Werdung von Wörtern durch das Vorhandensein von Frauen in deren Semantik [vgl. @pollatschek2022: 8]. Beispielsweise wurde "Prime Minister" durch Margaret Thatcher zu einem generischen Wort – und mit jeder weiteren Frau im Amt immer generischer. Im Deutschen führt sie das Beispiel von Frau und Fräulein an, das demnach vergleichbar sei [vgl. @pollatschek2022: 8]. Allerdings ignoriert ihre Argumentation, dass die deutsche Sprache eine Genussprache ist [vgl. @schütze2023: 143; @müller-spitzer2020: 53; @lind2022: 40 Anm. 22] und eine der stärksten Geschlechtsverankerungen in der Sprache hat [vgl. @bedijs2022: 43]. Entsprechend stellen Kristina Bedijs et al. fest, dass andere Genussprachen wie Spanisch, Portugiesisch oder Französisch ähnliche Probleme haben [vgl. @bedijs2022].

Trotz allem Streit, sind sich – zumindest in der Wissenschaft – über das Ziel der Geschlechtergerechtigkeit, das im Grundgesetz verankert ist (Art. 3 Abs. 2), alle einig. Somit stellt sich mehr die Frage nach der angemessenen sprachlichen Form als danach, *ob* geschlechtergerechte Sprache generell verwendet werden sollte [vgl. @müller-spitzer2022: 40]. Diese Perspektive geht häufig unter, zumal für ihre Beachtung deutlich mehr Konstruktivität notwendig wäre. Interessant – wenn auch eher für den gesellschaftlichen Bereich – ist die Sichtweise Henning Lobins in Anlehnung an Anatol Stefanowitsch [-@stefanowitsch2018]: Geschlechtergerechte Sprache beziehungsweise eine möglichst gewalt- und diskriminierungsfreie Sprache generell ist letztlich eine Frage der Höflichkeit gegenüber seinen Mitmenschen [vgl. -@lobin2018] – und damit eine Frage der Moral.

## Bundestagsanträge

Obgleich Bundestagsanträge ein etablierter Teil der parlamentarischen Arbeit darstellen, wurden und werden sie in der politikwissenschaftlichen Forschung wenig bis gar nicht berücksichtigt. Das ist durchaus erstaunlich, finden sich doch Analysen von parlamentarischen Anfragen zuhauf [siehe z. B. @bereswill2021; @siefken2010; @hünermund2018; @carstensen2018; @bald1988]. Einzig Wolfgang Ismayr widmet sich in seiner (auch nicht gerade neuen) Monographie über den Deutschen Bundestag den Anträgen im Bundestag [-@ismayr2012: 403-407].[^01-theorieteil-5] Somit kann sich diese Arbeit nur wenig auf den Stand der Forschung stützen und nimmt damit auch eine explorative Funktion für die Politikwissenschaft ein.

[^01-theorieteil-5]: Zwar ist Ismayrs Werk von 2012, jedoch handelt es sich um die 3., völlig überarbeitete und aktualisierte Auflage. Die Erstauflage erschien im Jahre 2000. Und auch seit 2012 hat sich das parlamentarische Umfeld (potentiell) mit dem Einzug der AfD geändert, sodass eine aktualisierte Betrachtung von Ismayrs Beschreibung des Antragsverhaltens und vielen weiteren Details durchaus geboten ist.

Bundestagsanträge sind ein Medium der politischen Kontrolle mit dem Ziel eines Parlamentsbeschlusses [vgl. @ismayr2012: 403]. Dabei entstehende Beschlüsse sind allerdings nicht rechtlich bindend für die Regierung und die Verwaltung – auch wenn sie als politisch verpflichtend wahrgenommen werden [vgl. @ismayr2012: 403].

Es können drei Arten von Anträgen unterschieden werden: (Selbstständige) *Anträge* befassen sich überwiegend mit politischen Sachfragen [@ismayr2012: 403]. *Entschließungsanträge* bieten den Fraktionen unter anderem die Möglichkeit, Berichte und Erklärungen der Regierung herbeizuführen oder auch zu Großen Anfragen und Gesetzesentwürfen und weiteren Vorlagen schriftlich Stellung zu nehmen und einen Beschluss herbeizuführen \[vgl. @ismayr2012: 403; vgl. § 75 GOBT[^01-theorieteil-6]\]. Mit *Änderungsanträgen* hingegen können bestehende Anträge geändert werden.\
Nach § 75 und 76 Absatz 1 GOBT können Anträge und Entschließungsanträge nur von einer Fraktion oder 5 % der Bundestagsmitglieder unterzeichnet sein. Dementsprechend wurden zwischen 1994 und 2009 auch nur 1,3 % der Anträge ohne eine Fraktionsbeteiligung eingereicht [vgl. @ismayr2012 403-405].

[^01-theorieteil-6]: Geschäftsordnung des Bundestages

Lediglich ein kleiner Teil der Anträge führt tatsächlich zu einem Parlamentsbeschluss [vgl. @ismayr2012: 403]. Das liegt daran, dass in der Praxis vor allem die Oppositionsfraktionen dieses Instrument nutzen, was von den Mehrheitsfraktionen in aller Regel abgelehnt wird [vgl. @ismayr2012: 403]. 85 % der Anträge des 16. Deutschen Bundestags kamen von der Opposition [vgl. @ismayr2012: 405]. Koalitionsfraktionen stellen Anträge dagegen meist gemeinsam und vermeiden kritische Töne gegenüber Regierung und Verwaltung [vgl. @ismayr2012: 405, 407]. Oft haben Anträge für die Mehrheitsfraktionen auch eine taktische Funktion, um Vorstöße aus dem Oppositionslager abzufangen und der Öffentlichkeit gegenüber das Gesicht zu wahren [vgl. @ismayr2012: 407]. Oppositionsfraktionen kooperieren im Gegensatz zu den Mehrheitsfraktionen nur höchst selten und wenn dann förmlich [vgl. @ismayr2012: 405]. Die Chancen für die Opposition, Sachanträge durchzubringen ist nicht nur deswegen sehr gering: "Nicht selten wird ein oppositioneller Antrag selbst dann abgelehnt und ihm gegebenenfalls ein Koalitionsantrag entgegengesetzt, wenn in der Sache kaum Meinungsunterschiede bestehen und dies – vor allem im Ausschuss – auch artikuliert wird" [@ismayr2012: 405]. In der 16. Wahlperiode wurde kein einziger Oppositionsantrag angenommen [vgl. @ismayr2012: 405], die größte Chance besteht dafür bei humanitären oder formalen Fragen [vgl. @ismayr2012: 405].

Trotz der geringen Chancen auf einen tatsächlichen Bundestagsbeschluss sind Anträge für die Opposition ein "unverzichtbares Mittel öffentlichkeitswirksamer Kontrolle und Einflussnahme" [@ismayr2012: 405], denn sie bieten Minderheitsfraktionen die Möglichkeit, gewollte Debatten zu selbstgewählten Themen durchzusetzen, da die Anträge innerhalb einer gewissen Frist behandelt werden müssen [vgl. @ismayr2012: 405]. Kein Wunder, dass die Nutzung solcher Anträge "in erheblichem Umfang" [@ismayr2012: 405] erfolgt.\
Anträge haben darüber hinaus eine wichtige Policy-Funktion: Sie sind oft ausgearbeitete Programme beziehungsweise Konzepte, die meist als Alternative zur Regierungspolitik präsentiert werden und oft mit Maßnahmenbündeln verknüpft sind [vgl. @ismayr2012: 407]. Teil von Anträgen sind häufig Problemanalysen und konzeptionelle Darlegungen, die entweder in Form einer ausführlichen Begründung angefügt oder im Antragstext thematisiert mitbeschlossen wird [vgl. @ismayr2012: 407].\
Die internen Abläufe in den Fraktionen während des Antragsprozesses ähneln dem von Gesetzesentwürfen [vgl. @ismayr2012: 406]. Im Abstimmungsprozess wird seit der 10. Wahlperiode zunehmend auch das Druckmittel der namentlichen Abstimmung eingesetzt [vgl. Saalfeld 1995: 55 ff. zit. n. @ismayr2012: 407].

In der Wissenschaft sind Bundestagsanträge ein äußerst unbeleuchtetes Feld. Dabei gilt dies sowohl für die Bewertung der Rolle im Politikprozess, also die Wichtigkeit und die Wirkmächtigkeit von Anträgen, als auch für Anträge als Ausdruck von politischen Überzeugungen, Themensetzungen und der Gewichtigkeit von Themen, mit anderen Worten: für die Operationalisierung latenter Konstrukte bezüglich der Bundestagsfraktionen. Stattdessen hat sich die wissenschaftliche Aufmerksamkeit auf Kleine und Große Anfragen fokussiert. Auch wenn das grundsätzlich nicht verwerflich ist, wäre eine Erschließung der Bundestagsanträge als Forschungsfeld sicher gewinnbringend und erkenntnisreich für politics-, aber auch policy-orientierte Forschung.

## Populismus

In der derzeitigen Öffentlichkeit ist Populismus ein "Kampfbegriff" [@lewandowsky2022: 1], er gleicht dem Vorwurf der Simplifizierung komplexer Sachverhalte – Opportunismus statt Konstruktivität [vgl. @lewandowsky2022: 14]. Die Basis scheint dabei die menschliche Tendenz zur Selbstbestätigung, der Aufrechterhaltung eines positiven Selbstbildes sowie die Favorisierung der Eigengruppe zu sein [vgl. @neubaum2022: 415]. Dass das Phänomen des Populismus allgegenwärtig ist, stellte schon Cas Mudde 2004 fest, als er von einem "populistischen Zeitgeist" [@mudde2004: 542] sprach. Folgend soll ein Überblick über gängige wissenschaftliche Definitionen, die Messung, das Verhältnis von Populismus und Social Media sowie von Populismus und Demokratie und nicht zuletzt über bestehende Forschungslücken gegeben werden.

In der Wissenschaft ist das Konzept Populismus umstritten, vor allem wegen der Wertgeladenheit und Unschärfe des Begriffs [vgl. @lewandowsky2022: 2; @decker2021: 776]. Eine der ersten wissenschaftlichen Auseinandersetzungen legten Lipset (1960), Shils (1956) sowie Ionescu und Gellner (1969) vor, die Populismus als Gespenst sahen, das die Welt heimsuche [zit. n. @lewandowsky2022: 12; @wirth2016: 7]. Lange Zeit gab es in der Forschung wenig bis keine theoretische Fundierung des Begriffs, stattdessen mehr eine Ad-hoc-Verwendung [vgl. @lewandowsky2022: 12]. Mittlerweile kann von einem regelrechten "Boom in der Forschung" [@decker2021: 777] gesprochen werden, der von ideologischen Inhalten, der Organisation und dem Auftreten, den Ursachen und Entstehungshintergründen bis hin zur Wirkung von Populismus reicht. Allerdings besteht nach wie vor eine Uneinigkeit über die Definition von Populismus [vgl. @merkle2016: 130]. Der Grund dafür: "[populism] manifests itself differently depending on the contextual conditions" [Priester 2007 zit. n. @engesser2017: 1111]. Kritik gibt es vor allem bezüglich der Populismusmessung [vgl. @lewandowsky2022: 36]. Anzumerken ist weiterhin, dass im Fokus der Forschung vor allem rechter Populismus steht [vgl. @heinze2022: 161].

Populismus zeichnet sich durch eine ideologische Varianz aus, weswegen es häufig als "Chamäleon" bezeichnet wird [vgl. @lewandowsky2022: 4; @engesser2017: 1114]. Als Stilmittel von Populismus fungieren nach Frank Decker und Marcel Lewandowsky der Rückgriff auf Common-Sense-Argumente, die Vorliebe für radikale Lösungen, Verschwörungstheorien und das Denken in Feindbildern, Provokation und Tabubruch, Emotionalisierung und Angstmache sowie die Verwendung von biologistischen und Gewaltmetaphern [-@decker2017: 29-30].

Die gängigste und wissenschaftlich hoch angesehene Definition für Populismus lieferte Cas Mudde mit dem Ideational Approach in den frühen 2000ern [-@mudde2004; @mudde2017: 34-36]. Seine Definition gilt als Minimalkonsens und Goldstandard [@lewandowsky2022: 18, 23; Hawkins et al. 2019 und Wirth et al. 2016 zit. n. @spieß2020: 224; @gehrmann2024: 4; @müller2016: 187] – zugleich ist sie ein Grundstein für die Populismusforschung [vgl. @heinze2022: 162] und Basis vieler folgender Definitionen [siehe z. B. @engesser2017: 1111]. Mudde definiert Populismus

> "as an ideology that considers society to be ultimately separated into two homogeneous and antagonistic groups, 'the pure people' versus 'the corrupt elite', and which argues that politics should be an expression of the volonté générale (general will) of the people." [@mudde2004: 543].

Demnach besteht Populismus aus Volkszentriertheit, einer Anti-Establishment-Haltung und einer angestrebten Wiederherstellung der Volkssouveränität.

Volkszentriertheit zeichnet sich durch die Vorstellung aus, "dass es ein durch einen gemeinsamen homogenen Willen gekennzeichnetes 'Volk' gebe" [@lewandowsky2022: 18]. Das "Volk"[^01-theorieteil-7] ist die ideologische Grundlage aller Populismusformen [vgl. @decker2021: 777]. Dabei entspricht das Volk nicht dem Staatsvolk [vgl. @lewandowsky2022: 18]. Die Homogenität des Volkes wird auf zwei Ebenen verstanden: einerseits bezüglich der Identität des Volkes [vgl. @lewandowsky2022: 18]. Demnach hat das Volk dieselben Interessen und Präferenzen, wobei der Common Sense des Volkes den Special Interests der Eliten gegenübersteht [vgl. @mudde2017: 33]. Während rechte Populist\*innen das Volk als gemeinsame Kultur oder Ethnie begreifen, liegt bei linken der Fokus mehr auf marginalisierten Gruppen [vgl. @lewandowsky2022: 19]. Die Konnotationen des Volkes sind dabei Aufrichtigkeit, Anstand, Fleiß oder auch der viel zitierte gesunde Menschenverstand [vgl. @lewandowsky2022: 19; @spieß2020: 225].[^01-theorieteil-8] Andererseits bezieht sich die Homogenität auf den politischen Willen des Volkes als Ganzes, den nur die Populist\*innen wirklich repräsentierten [vgl. @lewandowsky2022: 19-20]. Essentieller Teil von Populismus ist damit auch Antipluralismus [vgl. @mudde2004: 2004; @rensmann2006 63-64; @heinze2022: 163]. Wichtig ist, dass das Volk selbst eine "imagined community" [@mudde2004: 546] ist, die konstruiert ist und so nicht existiert [vgl. @mudde2017: 31-32].

[^01-theorieteil-7]: Das Volk ist hier ein ideologisches Konstrukt. Auf Anführungszeichen wurde der Lesbarkeit halber trotzdem verzichtet. Nachfolgende Verwendungen des Begriffs sind vor dem Hintergrund des Populismus-Begriffs zu sehen.

[^01-theorieteil-8]: Darauf aufbauend hat Paul Taggart das Konzept des Heartlands entwickelt [-@taggart2004]. Dieses entspricht "eine\[r\] Verklärung der Werte und Eigenschaften, die 'das Volk' ausmachen und die zugleich in einer glorifizierten Vergangenheit liegen, die wiederhergestellt werden müsse" [@lewandowsky2022: 19].

Populist\*innen sehen Volk und Elite als "schwarz" und "weiß" [vgl. Meyer 2006: 82 zit. n. @spieß2020: 225], wobei der Unterschied zwischen beiden normativ, nicht empirisch ist [vgl. @mudde2004: 544]. Überhaupt ist Moral die Basis für die Abgrenzung des Volkes zu den Eliten [vgl. @mudde2017: 32], weitere Dimensionen wie Klasse oder Nation werden durch die Ergänzung anderer Ideologien möglich [vgl. @mudde2017: 32].

Unter der Anti-Establishment-Haltung wird die Ablehnung der "Elite" verstanden, die ebenso als eine homogene Gruppe konstruiert wird [vgl. @lewandowsky2022: 20] und die Antithese des Volkes darstellt [vgl. @mudde2017: 32]. Im Fokus dieser Ablehnung steht die Behauptung, dass die Elite, womit verschiedenste Formen (politisch, kulturell, intellektuell, wirtschaftlich,...) gemeint sein können [vgl. @mudde2017: 33], nur ihren eigenen Interessen folgt und sich auf Kosten des Volkes bereichert [vgl. @spieß2020: 225; @mudde2004: 546]. Die Elite ist "korrupt, inkompetent, abgehoben, entrückt vom Volk und seinen Nöten" [@lewandowsky2022: 21] und kreiert Probleme, die mit den Problemen der kleinen Leute nichts zu tun haben [vgl. @schmiege2023: 438; @mudde2017: 33].

Schließlich steht die Wiederherstellung der Volkssouveränität für die Forderung, die Macht in die Hände des Volkes (zurück) zu geben [vgl. @spieß2020: 225]. Die Politik soll sich demnach vollständig durch den Volkswillen formen, wodurch konstitutionelle Elemente der liberalen Demokratie (unter anderem Gewaltenteilung, Schutz von Minderheiten) implizit oder explizit in Frage gestellt werden [vgl. @spieß2020: 225-226].

In der Praxis wird Populismus mit anderen Ideologien kombiniert, das Verständnis von Volk und Eliten ist dann je nach "Wirtsideologie" verschieden [vgl. @mudde2017: 32].\
Ein Beispiel dafür ist der Rechtspopulismus, bei dem Exklusion als weitere Dimension hinzukommt [vgl. @decker2017: 23; @spieß2020: 225]. Exkludiert werden "die Anderen", die das Volk – im Gegensatz zur Elite – von unten bedrohen [vgl. Reinemann et al. 2017 zit. n. @spieß2020: 226]. Nach Cas Mudde (2007) gehört zu Rechtspopulismus abgesehen von Nativismus auch noch Autoritarismus [zit. n. @decker2021: 777]. Doch auch wenn Populismus eine ideologische "Affinität nach rechts" [@rensmann2006: 76] hat und Rechtspopulismus gerade in Westeuropa sehr dominant ist, gibt es in anderen Regionen wie Lateinamerika oder Südeuropa teils sogar eine lange Tradition an linkem Populismus [vgl. @decker2006: 23].

Aufbauend auf Muddes Ansatz entwickelte Jan-Werner Müller eine Definition, die einen leicht anderen Fokus hat und sich bezüglich des Volonté Générale darüber hinaus auch inhaltlich absetzt [vgl. @müller2016]. Genau wie bei Mudde ist das zentrale Kriterium der "dezidiert moralische Anspruch, dass einzig die Populisten das wahre Volk vertreten" [@müller2016: 188]. Dieser ist demnach wie auch die Elitenkritik ein notwendiges, wenn auch nicht hinreichendes Kriterium für Populismus [vgl. @müller2016: 188]. Müller betont auch, dass ein charismatisches Führertum nicht automatisch vorhanden sein muss [vgl. -@müller2016: 190], was ja auch das Beispiel der AfD in Deutschland zeigt. Im Populismus sieht er einen Widerspruch zur Demokratie, die "nur das freie, nicht das imperative Mandat \[kennt\]" [@müller2016: 189]. Der zentrale Unterschied zu Mudde ist der Volonté Générale, der für Müller eher "Volksgeist" [@müller2016: 189] ist, da der Bezug zu Jean-Jacques Rousseau nicht plausibel sei. Denn: "Bei Rousseau mussten die einzelnen Bürger wirklich selber entscheiden, was sie für den allgemeinen Willen (und damit das Gemeinwohl) hielten. \[...\] Der Populist hingegen erkennt das Gemeinwohl der authentischen Nation auch so." [@müller2016: 189]. Müllers Verständnis von Populismus ist also sehr ähnlich zu dem von Mudde, unterscheidet sich jedoch beim Volksgeist beziehungsweise dem Volonté Générale. In der Forschung findet diese Weiterentwicklung durchaus Zuspruch [vgl. @franzmann2020: 12].

Abseits dessen gibt es auch andere Ansätze als den Ideational Approach, die sich teilweise auf einer anderen Ebene mit Populismus beschäftigen.\
Jan Jagers und Stefaan Walgrave entwickelten eine Unterscheidung, die auf Muddes Ansatz aufbaut [2007 zit. n. @merkle2016: 132; vgl. @jansen2020: 144]: Empty-Populismus beinhaltet demnach nur Volkszentriertheit, Excluding-Populismus Volkszentriertheit und Ausgrenzung, Anti-Eliten-Populismus Volkszentriertheit und Anti-Eliten-Haltung und zuletzt Complete-Populismus, der alle Bestandteile vereint.\
Eine andere Perspektive betrachtet Populismus als vollwertige Ideologie [vgl. @lewandowsky2022: 23]. Das bedeutet, "dass Populismus […] eine umfassende Deutung der sozialen Wirklichkeit und ein auf alle gesellschaftlichen Bereiche ausstrahlendes normatives Ideal beinhaltet" [Rydgren 2017: 488-489 zit. n. @lewandowsky2022: 23]. Die Charakteristika ähneln allerdings sehr dem, was man gemeinhin unter Rechtspopulismus versteht [vgl. @lewandowsky2022: 24].\
Die Gegenposition sieht Populismus als Thin Ideology [vgl. @mudde2004: 544; @lewandowsky2022: 23]. Das zentrale Argument ist, dass beim Populismus lediglich das Verhältnis zwischen Volk und Eliten definiert wird, nicht aber eine umfassende Deutung der sozialen Wirklichkeit vorgenommen wird [vgl. @lewandowsky2022: 24; @mudde2004: 544; @mudde2017: 30]. Wer und was genau das Volk ist, hängt dann von einer "Wirtsideologie" [@lewandowsky2022: 24; vgl. auch @mudde2004: 544] ab. Auf diese Weise können Differenzen zwischen Rechts- und Linkspopulismus sehr gut erklärt werden [vgl. @wirth2016: 9].\
Wieder andere verstehen Populismus als Diskurs [vgl. @ernst2017: 1348; @lewandowsky2022: 23], der Fokus liegt dabei auf Kommunikation als Struktur und die Akteure sind Träger von Sprechakten [vgl. @lewandowsky2022: 25].\
Eine weitere Perspektive ist Populismus als Stilmittel oder Strategie [vgl. @spieß2020: 224; @ernst2017: 1348; @lewandowsky2022: 23]. Kennzeichen dafür sind der Appell an das Volk, das Narrativ der Krisensituation, die Handeln notwendig macht, und schließlich die schlechten Manieren des populistischen Anführers, der dadurch als einfacher Bürger wahrgenommen wird und sich somit von der Elite distanziert [vgl. @lewandowsky2022: 26].\
Darüber hinaus gibt es auch noch zahlreiche weitere, die allerdings an dieser Stelle nicht weiter vertieft werden sollen [siehe @spieß2020: 224; @ernst2017: 1348; @froböse2020: 28].

Die Messung von Populismus ist empirisch herausfordernd [@wirth2016: 5]. In der Vergangenheit wurde definitorisch oft nicht sauber gearbeitet [vgl. @rensmann2006: 62], wodurch der Vorwurf der Unschärfe und inhaltlichen Beliebigkeit im Raum stand [vgl. Decker 2004: 23 ff. zit. n. @decker2006: 12]. Eine andere Schwierigkeit ist, dass die Souveränität des Volkes ein zentrales Element fast aller Demokratiekonzepte ist, wodurch die klare Zuordnung zu Populismus nicht eindeutig ist [vgl. @wirth2016: 9]. In eine ähnliche Schwierigkeit ist die Einordnung von Grenzfällen [vgl. @heinze2022: 163]. Nicht zuletzt besteht aber auch das grundsätzliche Problem, dass die meisten Parteien populistische Rhetoriken nutzen [vgl. @mudde2004: 562; siehe auch @engesser2017]. Auch Werner Wirth et al. stellen fest: "every politician tends to be 'populist' to a degree; the important question is how populist they are." [-@wirth2016: 35].

Im Folgenden gibt es einen kleinen Überblick über einige Herangehensweisen aus der Wissenschaft, um Populismus messen zu können. Dabei handelt es sich teils um Ergebnisse von großangelegten Studien, aber auch um die Datenbasis für die Messung von Populismus.\
*PopuList* bietet einen Überblick über populistische, weit-linke und weit-rechte Parteien in Europa zwischen 1989 und 2022. Die Einschätzung erfolgt auf Basis qualitativer Expert\*inneninterviews [vgl. @rooduijn2023].\
Das *Manifesto Project* bietet einen umfangreichen Textkorpus, in dem Wahlprogramme in Quasi-Sätze kodiert wurden, um sie auswertbar zu machen [vgl. @lehmann2024].\
In der *Global Populism Database* werden Daten zu Populismus gesammelt. Unter anderem gibt es Daten über den Populismusgrad von Reden von Staats- und Regierungschefs zwischen 2000 und 2018 [vgl. @lewandowsky2022: 30].\
*GermaParl* ist ein Textkorpus mit Plenarprotokollen des Deutschen Bundestags, auf den über ein R-Package zugegriffen werden kann [vgl. @blätte].

Populismus auf Social Media wurde schon vielfach analysiert [vgl. @spieß2020: 220; @degen2023: 40]. Die meisten Autor\*innen vertreten die Ansicht, dass Social Media die Logik des Populismus begünstigen [vgl. @engesser2017: 1113; anders: @neubaum2022: 420], vor allem, weil dort eine viel direktere, ungefilterte [vgl. @engesser2017: 1113; @spieß2020: 221; @ernst2017: 1350] Verbindung zur Zielgruppe besteht, die überdies noch den Journalismus als Gatekeeper umgeht [vgl. @spieß2020: 222; @ernst2017: 1350; @wirth2016: 28]. Soziale Medien stellen ein wichtiges Kommunikationsinstrument dar, über das Parteien und Politiker\*innen informieren und Diskussionen auslösen [vgl. @spieß2020: 221] – und damit dem grundgesetzlichen Anspruch, an der politischen Meinungsbildung beteiligt zu sein, gerecht werden. Trotzdem zeigt sich auch, dass populistische Kommunikation beispielsweise auf Facebook gut funktioniert [vgl. @spieß2020: 222; @degen2023] und dass Populisten häufig in Parlamenten moderater als im außerparlamentarischen Raum auftreten [vgl. @heinze2022: 169]. Bartlett sieht Social Media aus oben genannten Argumenten sogar als ideales Medium für Populist\*innen [vgl. 2014: 106 zit. n. @spieß2020: 222].

Hinsichtlich der Frage, inwiefern Populismus eine Gefahr für die Demokratie darstellt, gibt es in der Forschung unterschiedliche Ansichten, die hier nur angerissen werden sollen. Die wissenschaftliche Meinung schwankt darin, Populismus als Bedrohung oder als Korrektiv zu sehen [vgl. @ernst2017: 1348], wobei vergleichsweise wenige Autor\*innen die Korrektiv-Seite vertreten. Zur Frage, ob Populismus eine Gefahr für die Demokratie oder ein nützliches Korrektiv darstellt, gibt es sogar einen ganzen Sammelband [@populism2006]. Mudde sieht mehr den Rechtspopulismus als Gefahr als den Populismus an sich [2019 zit. n. @heinze2022: 162]. Lars Rensmann attestiert dem Populismus langfristig problematische Effekte und sieht die Gefahr, er könne in Extremismus umschlagen [vgl. @rensmann2006: 77]. Ähnlich sehen es Wirth et al.: "populist democracy is illiberal" [-@wirth2016: 16].

Auch wenn Populismus als Phänomen in großem Maße erforscht wurde, stellt Anna-Sophie Heinze einige Forschungsdesiderate heraus, die größerer Aufmerksamkeit bedürfen. Dies sind die Betrachtung von Prozessen auf subnationaler Ebene, den Fokus von der Parteipolitik auf die nichtelektorale Ebene zu weiten, rechtsradikale Phänomene mehr aus der Binnenperspektive zu untersuchen und zuletzt den Fokus auf effektive Strategien zur Stärkung der liberalen Demokratie zu richten [vgl. @heinze2022: 170]. Darüber hinaus ist festzuhalten, dass Populismus aufgrund seiner Aktualität und Beständigkeit ein immer weiter zu erforschendes Phänomen bleiben wird – auch über die hier beschriebenen Lücken hinaus.

## Polarisierung geschlechtergerechter Sprache

Im Oktober 2023 veröffentlichten Steffen Mau, Thomas Lux und Linus Westheuser [-@mau2024] ein in der Forschung wie in der Öffentlichkeit vielbeachtetes Buch, in dem sie die vielfach vertretene Polarisierungsthese empirisch widerlegen und explorativ einen Erklärungsansatz entwickeln, warum bestimmte Themen trotzdem den Anschein der Spaltung vermitteln. In diesem Teil werden nun die wichtigsten Punkte dieses theoretischen Ansatzes vorgestellt.

Die Polarisierungsthese oder auch Zwei-Lager-Theorie, nach der es zwei Lager mit widerstreitenden Meinungen, Interessen und Werten gäbe, wurde in den vergangenen Jahren und Jahrzehnten immer präsenter [vgl. @mau2024: 7; 9]. Polarisierung an sich kann in eine dünne und eine dicke (soziologische) Auslegung unterschieden werden: Die "(wachsende) Diskrepanz von politischen Einstellungen und von Wählerschaften" [@mau2024: 14] steht einer Diskrepanz nach Cleavages beziehungsweise Klassen gegenüber [@mau2024: 14]. Der wichtigste und zugleich überraschende Befund der Arbeit von Mau et al. lautet, dass das Bild einer gespaltenen Gesellschaft gar nicht zutrifft [-@mau2024: 25]. Die affektive Polarisierung, also "Gefühle von Sympathie und Antipathie, die gegenüber ideologischen und sozialen Fremdgruppen eingenommen werden" [@mau2024: 28], hat sogar seit 2000 abgenommen [@mau2024: 18]. "Das breite Zentrum ist demgegenüber relativ entideologisiert und wenig auf Abgrenzung bedacht – wiederum mit Ausnahme der Abgrenzung gegenüber der AfD" [@mau2024: 30]. Demnach besteht zwar eine Politisierung, die allerdings ohne Polarisierung stattfindet [vgl. @mau2024: 384]. Die (irrtümliche) Wahrnehmung einer gespaltenen Gesellschaft (*false polarization*) findet ihre Ursachen vermutlich in der Leidenschaftlichkeit und Unnachgiebigkeit aktueller politischer Konflikte [vgl. @mau2024: 20; 378].

### Vier Ungleichheitsarenen

Alle relevanten Konflikte der heutigen Zeit sind Ungleichheitskonflikte, also "gesellschaftlich verankerte Formen der Begünstigung und Bevorrechtigung einiger, der Benachteiligung und Diskriminierung anderer" [Kreckel zit. n. @mau2024: 21]. Mau et al. wählen das Konzept der Arena in Anlehnung an die Arenen der Antike als Schauplätze des Wettkampfes [vgl. @mau2024: 38]. Sie unterscheiden dabei vier Arenen, in denen jeweils ähnliche Konflikte ausgetragen werden und die im Folgenden kurz dargestellt werden.

In der *Oben-Unten-Arena* werden Verteilungskonflikte ausgetragen, es geht also um Ressourcen und Ansprüche, die sich innerhalb der Sozial-, Verteilungs- und Steuerpolitik bewegen. Die Triebkraft dabei ist die "Rückkehr der Ungleichheit", wobei sich auf Klassen und Schichten sowie Reiche und Arme im Kollektiv bezogen wird. Bearbeitet werden Oben-Unten-Konflikte über Umverteilung und Absicherung, die Verteilungsbilanz ist ein Nullsummenspiel [vgl. @mau2024: 49].

*Innen-Außen-Ungleichheiten* zielen auf Zugehörigkeits- und Grenzkonflikte, es geht also um Zugang und Mitgliedschaft zur Gesellschaft. Das betrifft die Felder der Migrations- und Integrationspolitik, die vor allem von einer Transnationalisierung und Migration getrieben werden. In dieser Arena wird sich auf Inländer und Ausländer, Eingesessene und Migranten bezogen. Die Bearbeitung erfolgt über Inklusion und Integration, wobei die Verteilungsbilanz unklar ist [vgl. @mau2024: 49].

In der *Wir-Sie-Arena* wird um Anerkennungskonflikte gestritten, in denen Rechte und Anerkennung im Mittelpunkt stehen. Ein zunehmender Wertewandel und Entkonventionalisierung sind Triebkräfte der Konflikte, die sich im Rahmen der Gleichstellungs- und Anerkennungspolitik bewegen und anhand von Gleichstellung, Quoten und Normenwandel bearbeitet werden. Etablierte stehen dabei Außenseitern gegenüber. Die Verteilungsbilanz ist zwar ein Positivsummenspiel, das aber Statusverluste implizieren kann [vgl. @mau2024: 49].

In der Arena der *Heute-Morgen-Ungleichheiten* sind Umweltgüter und Zeit die Streitpunkte – es geht um ökologische und Zeitkonflikte, die sich vor allem in der Umwelt- und Klimapolitik abspielen. Triebkräfte sind in erster Linie die Klimakrise, fossile Produktion und Lebensweise. Verursacher werden Betroffenen gegenübergestellt, die Bearbeitung erfolgt über Transformation und Nachhaltigkeit. Die Verteilungsbilanz ist eine Negativsumme bei Nicht-Handeln, die allerdings Zielkonflikten unterliegt.

### Wir-Sie-Arena

Der gesellschaftliche Konflikt um geschlechtergerechte Sprache ist Teil der Wir-Sie-Arena, weswegen diese nochmal ausführlicher behandelt wird. Auszeichnend für Wir-Sie-Ungleichheiten sind "gruppenspezifische Erfahrungen der Missachtung oder Diskriminierung \[, die\] mit *Forderungen nach Anerkennung* \[Hervorhebung im Original\] beantwortet und so die Trägerschichten der dominanten Kultur herausgefordert werden." [@mau2024: 60]. Es geht also um die "Einbeziehung von Subjekten in den Kreis der vollwertigen Gesellschaftsmitglieder" [Honneth zit. n. @mau2024: 60], gerungen wird um Normalitäten und um Sanktionen für Abweichungen [vgl. @mau2024: 160], denn: für Anerkennung muss die privilegierte Lebensform relativiert oder zurückgestuft werden [vgl. @mau2024: 60]. Nicht selten wird auf die Meinung der "normalen" Bevölkerung verwiesen – wie schon gezeigt, ist dies ein populistisches Instrument [vgl. @mau2024: 166].[^01-theorieteil-9]

[^01-theorieteil-9]: Wir-Sie-Konflikte werden oft als Identitätspolitik betitelt, also "aufgrund von Gruppenzugehörigkeiten gemachte Abwertungs- oder Ausgrenzungserfahrungen \[, die\] zum Ausgangspunkt politischen Handelns werden" [@mau2024: 61]. Das ist einerseits ungenau, da mit diesem Prozess auch materielle Verteilungskämpfe einhergehen [vgl. @mau2024: 163], andererseits unterstellen Konservative oft die Unterwerfung der Mehrheitsbevölkerung durch eine kleine Gruppe radikaler Minderheiten, was wiederum Identitätspolitik darstellt [vgl. @mau2024: 165].

Die Wir-Sie-Arena bestimmt ein weitgehender Konsens über die Ablehnung von Diskriminierung. Es gibt eine große Zustimmung zu einer vielfältiger und bunter werdenden Gesellschaft, die nur von Minderheiten infrage gestellt wird [vgl. @mau2024: 167]. Mit Daten des *European Social Survey (ESS)* kann ein klarer Liberalisierungstrend festgestellt werden [vgl. @mau2024: 169], frühere Streitpunkte wie die Homo-Ehe sind heutzutage indiskutabel [vgl. @mau2024: 170]. Selbst "wo offizielle gendersensible Sprachregelungen abgelehnt werden \[…\], werden sie in Bezug auf eine individuelle Person respektiert." [@mau2024: 182]. Der Streitpunkt ist also weniger, ob "Ja" oder "Nein", sondern mehr ob "Ja" oder "Ja, aber" [vgl. @mau2024: 199].

Weitgehender Konsens besteht auch über eine Erlaubnistoleranz, also die Tolerierung anderer Lebensformen und Identitäten unter dem Vorzeichen der legitimen Indifferenz [vgl. @mau2024: 173]. Dabei wird eine Perspektive der Mehrheitsgesellschaft eingenommen, die Diversifizierung als Irritationsmoment begreift [vgl. @mau2024: 175]. Die Minderheit darf demnach schon nach eigener Maßgabe leben, insofern sich die Mehrheit nicht gestört fühlt [vgl. @mau2024: 176].

Genauso ist eine Unsicherheit über Begrifflichkeiten in der Breite festzustellen [vgl. @mau2024: 202].

Auf der Dissens-Seite können die Meinungen zu einem Konflikt zwischen Erlaubnistoleranten und Respekttoleranten aggregiert werden. Respekttoleranz ist eine progressive Erweiterung der Erlaubnistoleranz nach Rainer Forst [vgl. @mau2024: 183], die mehr die Außenseiter- statt die Etabliertenperspektive einnimmt [vgl. Elias/Scotson zit. n. @mau2024: 181]. Es handelt sich um einen kompensatorischen Ansatz, der andere als moralisch und ethisch Gleiche anerkennt und Unterschiede aufgreift, um eine größere symbolische Repräsentanz herzustellen [vgl. @mau2024: 183-184]. Es findet somit eine Umwertung statt. Wenn Anerkennung über ein reines Hinnehmen, also über Erlaubnistoleranz hinausgehen soll, sind Vorbehalte gegenüber Diversität zu beobachten [vgl. @mau2024: 399].

Dementsprechend unterscheidet sich einerseits die Problemwahrnehmung: Halten Erlaubnistolerante die Diskriminierung für weitgehend überwunden, sehen Respekttolerante, dass diese immer noch allgegenwärtig ist [vgl. @mau2024: 202].

Andererseits unterscheidet sich die Strategie des Diskriminierungsabbaus: Während die konservative Position eine stillschweigende Eingemeindung präferiert – die Anerkennung als Normale –, zielt die progressive Position auf eine öffentliche Umwertung – die Anerkennung als Besondere und Gleiche. Daraus folgt auf der einen Seite das Ablehnen von Sonderrechten und auf der anderen Seite die Forderung nach einem Nachteilsausgleich. Konservative betrachten die geforderten Veränderung dann oft als Zumutung, wohingegen Progressive die Pflicht zur Selbsthinterfragung sehen [vgl. @mau2024: 202].

Hinsichtlich geschlechtergerechter Sprache zeigt sich eine "Irritation über Begriffsneuerungen, die Wahrnehmung einer zu Unrecht in die Öffentlichkeit gezerrten Thematik sowie die Abwehr 'übertriebener' Forderungen und einer vermeintlichen Hypersensibilität." [@mau2024: 191]. Dabei ist die Polarisierung nicht besonders hoch [vgl. @mau2024: 195]. Erstaunlich ist, dass keine Klassenkonfrontation zwischen Akademiker\*innen und Arbeiter\*innen festgestellt werden konnte [vgl. @mau2024: 195], der Vorwurf von Kritiker\*innen, Ungleichheitskritik käme vor allem von Bessergestellten und höher Gebildeten, den sogenannten "Lifestyle-Linken" [@wagenknecht2022] kann zurückgewiesen werden [@mau2024: 175].

### Triggerpunkte

Um die Heftigkeit mancher Konflikte erklären zu können, bedienen sich Mau et al. dem Konzept der Triggerpunkte: "sensible Bereiche des öffentlichen Diskurses \[…\], wo Menschen stark und affektiv reagieren" [@mau2024: 27]. Sie sind "neuralgische \[…\] Stellen, an denen Meinungsverschiedenheiten hochschießen, an denen Konsens, Hinnahmebereitschaft und Indifferenz in deutlich artikulierten Dissens, ja sogar Gegnerschaft umschlagen." [@mau2024: 246]. Der Schwachpunkt des öffentlichen und teils auch wissenschaftlichen Diskurses, so die Autoren, ist der Schluss von medialen Diskursformen auf eine polarisierte Tiefenstruktur der Gesellschaft [vgl. @mau2024: 245].

In einer Taxonomie typischer Trigger stellen Mau et al. dar, welche Erregungsgründe zu Triggern werden können: *Ungleichbehandlungen* (verletzte Erwartung: Egalität), *Normalitätsverstöße* (verletzte Erwartung: Normalität), *Entgrenzungsbefürchtungen* (verletzte Erwartung: Kontrolle) und nicht zuletzt *Verhaltenszumutungen* (verletzte Erwartung: Autonomie) [vgl. @mau2024: 276].

So ist es leicht verständlich, dass "\[s\]prachpolitische Interventionen \[…\] auf starke Reaktanz \[treffen\]" [@mau2024: 400], denn geschlechtergerechte Sprache erfüllt gleich alle vier dieser Triggertypen. Als "Sonderrecht" für Minderheiten ist es ein Trigger für Ungleichbehandlung, als Abweichung von den gängigen Sprachnormen ein Trigger für Normalitätsverstöße, als Praxisform im kommunikativen Umgang miteinander – ob in den Nachrichten oder in der Firma – ein Trigger für Entgrenzungsbefürchtungen und als "Sprachreform" ein Trigger für Verhaltenszumutungen.

### Sozialstrukturelle Polarisierung

Überraschenderweise stellt die Studie auch fest, dass es zwar eine Klassenspezifik gibt, nicht aber eine Klassenpolarisierung [vgl. @mau2024: 290], denn die Unterschiede der Klassen sind marginal – genauso wie die des Alters, von Bildung, Stadt und Land sowie Ost und West [vgl. @mau2024: 292, 297, 300, 301]. Einzig beim Geschlecht zeigt sich, dass Frauen eine höhere Akzeptanz sexueller Vielfalt haben als Männer [vgl. @mau2024: 302].

### Polarisierungsunternehmer

Dass Triggerpunkte von politischen Akteuren bewusst genutzt werden können, scheint offensichtlich. Politische Akteure, "deren Profilierung primär über die Erzeugung und Kapitalisierung polarisierter Auseinandersetzung erfolgt", nennen @mau2024 \[: 375\] Polarisierungsunternehmer. Insbesondere die AfD versucht auf diesem Wege, politische Geländegewinne zu realisieren, Berührungsängste abzumildern und so einen Kulturkampf zwischen rechtskonservativ und linksgrün zu inszenieren [vgl. @mau2024: 377].

Triggerpunkte werden aber auch von etablierten Akteuren genutzt, um sich von anderen Parteien abzusetzen [vgl. @mau2024: 388]. Social Media begünstigen diese Mechaniken [vgl. @mau2024: 335-336].

## Theoretische Überlegungen

Thema: Populismusgrad der Social-Media-Kommunikation der Parteien über geschlechtergerechte Sprache

### Definitionen

Populismus wird in dieser Arbeit angelehnt an Cas Mudde als eine dünne Ideologie definiert, die im Wesentlichen aus den Aspekten Volksnähe, Elitenkritik und der Wiederherstellung der Volkssouveränität besteht [-@mudde2004: 543].

Als geschlechtergerechte Sprache wird der Versuch verstanden, Geschlechtergerechtigkeit in der Sprache herzustellen, wobei ein wichtiger Bestandteil die Sichtbarmachung von in der Sprache nicht abgebildeten Geschlechtern ist [vgl. @rödder2022: 6].

…

-   Forschungsfragen (ggf. in Einleitung)

-   Relevanz (ggf. in Einleitung)

### Analyse von Individualdaten

-   zu erwarten, dass alle keinen großen Einfluss

### Analyse von Bundestagsanträgen

Im Kern dieser Analyseebene steht die These, dass vor allem rechte und mit Einschränkungen konservative Parteien geschlechtergerechte Sprache thematisieren, um sie als Triggerpunkt für ihre Zwecke zu missbrauchen. Sie schlüpfen, um mit @mau2024 zu sprechen, in die Rolle der Polarisierungsunternehmer, die bewusst versuchen, einen Kulturkampf zu inszenieren, um von der daher erhofften Spaltung zu profitieren. Hypothese H2.1 lautet demnach, dass die AfD geschlechtergerechte Sprache am meisten in Bundestagsanträgen thematisiert.

### Analyse von Facebook-Posts

Zunächst ist zu vermuten, dass aufgrund der günstigen Rahmenbedingungen auf Social Media populistische Parteien – als Grundlage der Bewertung wird die PopuList [@rooduijn2023] genutzt, nach der das auf die AfD sowie Die Linke als Grenzfall zutrifft – die Plattform Facebook besonders häufig nutzen, also erkennbar mehr Posts absetzen als die übrigen Parteien (H3.1). Darauf aufbauend wird vermutet, dass die Posts dieser Parteien zu geschlechtergerechten Sprache populistischer sind als bei anderen Parteien, da populistische Parteien auch zu populistischer Kommunikation neigen sollten (H3.2). Wie schon im Zuge der Hypothese H2.1 angesprochen, wird die AfD als Polarisierungsunternehmer angesehen, sodass zu erwarten ist, dass wie auch bei den Bundestagsanträgen die AfD am meisten geschlechtergerechte Sprache thematisiert (H3.3). Da es sich bei geschlechtergerechter Sprache um einen gesellschaftlichen Triggerpunkt handelt, ist anzunehmen, dass im Bundestagswahlkampf besonders viele Posts zu diesem Thema abgesetzt wurden, um davon zu profitieren [vgl. @mau2024: 388] (H3.4). Zuletzt wird vermutet, dass Posts, in denen der Schwerpunkt auf geschlechtergerechter Sprache liegt, populistischer sind als Posts, die geschlechtergerechte Sprache nur am Rand thematisieren (H3.5).
