# Zusammenfassung

Wird geschlechtergerechte Sprache vornehmlich von Rechtskonservativen und vor allem der AfD thematisiert? Diese Frage lässt sich nun eindeutig mit Ja beantworten. Aber eines nach dem anderen.

In der ersten Analyseebene konnte festgestellt werden, dass die Befunde von Mau et al. anhand der vorliegenden Daten, die einige Schwächen haben, nicht widerlegt werden konnten. Auch beim so kontroversen Thema der geschlechtergerechten Sprache, das ein so hohes Maß an Triggerpotential aufweist, scheint es also keine gesellschaftliche Polarisierung zu geben. Das ist erstaunlich, wird doch gerade bei diesem Thema von Medien und Diskursteilnehmer\*innen oft auf eine Polarisierung verwiesen. Nichtsdestotrotz erfordert es weitere Forschung mit besseren Daten, um diese Erkenntnisse auf standfestere Beine zu stellen. Ideal wäre eine Untersuchung, die an die empirischen Erkenntnisse von @mau2024 anschließt.

Wie schon angedeutet hat sich in der zweiten Analyseebene gezeigt, dass fast ausschließlich die AfD geschlechtergerechte Sprache mittels Bundestagsanträgen thematisiert. Das lässt die Vermutung aufsteigen, dass die AfD bewusst dieses Triggerthema ins deutsche Parlament schleust, um die übrigen Fraktionen und über die mediale Aufmerksamkeit auch die deutsche Gesellschaft zu polarisieren und sich zu einem Standpunkt zu bekennen. Des weiteren konnte gezeigt werden, dass sich das Antragsverhalten mit einer Regierungsbeteiligung deutlich verändert. Bestehende Erkenntnisse von @ismayr2012 wurden so auf eine aktuellere Datenbasis gestellt.

Den Befund, dass vor allem die AfD geschlechtergerechte Sprache auf die (gesellschaftliche) Tagesordnung bringt, bestätigt auch die dritte und letzte Analyseebene, die sich Facebook-Posts widmete und diese auf ihren Populismusgehalt untersuchte. Zunächst konnte festgestellt werden, dass rechtskonservative Parteien überdurchschnittlich viele Posts auf Facebook absetzen, Facebook scheint also in parteilicher Hinsicht ein rechtskonservatives Medium zu sein – das allerdings immer weniger verwendet wird, die Post-Zahlen sind rückläufig. Außerdem wurde herausgefunden, dass das Postverhalten abhängig vom Wahlkampf sein könnte. Weitergehende Forschung könnte an dieser Stelle ansetzen und sich auch Zusammenhängen mit populistischer Kommunikation widmen. Zuletzt – und das ist wohl der entscheidende Befund – stellte sich heraus, dass ausschließlich die AfD und die CSU populistische Posts zum Thema geschlechtergerechter Sprache veröffentlichten – und das besonders häufig im Wahlkampf. Das legt tatsächlich die Vermutung nahe, dass geschlechtergerechte Sprache aktiv als Triggerpunkt genutzt wird, um politisch davon zu profitieren. Das Konzept der Triggerpunkte könnte ein Erklärungsmodell für solche sensiblen Bereiche des öffentlichen Diskurses sein, die Menschen zu einer starken und affektiven Reaktion drängen und das es weiter zu untersuchen gilt. Zukünftige Forschung könnte neue und weitere Erkenntnisse zur Erklärung liefern und sich explorativ auch einer gesellschaftlichen Perspektive widmen, wie ein sinnvoller Umgang damit sein kann.
