# Wenn Sie unten einen Teil haben, den Sie noch nicht verfasst haben, dann können Sie ihn mit # auskommentieren (nur nicht index.Rmd)

project:
  type: book
  output-dir: Bachelorarbeit # anpassen

Entwurfstatus: Entwurf 0.0 # regelmässig anpassen und am Ende auskommentieren (# an Anfangs)

#institute: Institut für Politikwissenschaft
#AG: X
#Uebung: 0
#TutorIn: Vorname Nachname
Modul: 'Bachelorarbeit'
Semester: 'SoSe 24'
Erstgutachter: 
 - name: Prof. Dr. Isabelle Bourcki
 - Email: borucki@uni-marburg.de
Zweitgutachter:
 - name: Stine Ziegler
 - Email: stine.ziegler@uni-marburg.de
Datum: "23.08.2024"

book:
  title: 'Politisierung geschlechtergerechter Sprache' # eher knackig
  subtitle: 'Bachelorarbeit' # bessere Beschreibung 
  author:
  - given-names: Jakob
    surname: Krueger
    Email: Kruege4c@students.uni-marburg.de
    MatrikelNr: 3583647
    Studiengang: B.A. Politikwissenschaft

  chapters:
    -  index.qmd
    -  01-Theorieteil.qmd
    -  02-Methode.qmd 
    -  03-Ergebnisse-sui.qmd
    -  04-Ergebnisse-bta.qmd
    -  05-Ergebnisse-sm.qmd
    -  07-Schluss.qmd
  appendices:
    -  08-Anhang.qmd

  downloads: [pdf]
  output-file: Bachelorarbeit_Krueger_polges

bibliography: files/references.bib
cite-method: citeproc
csl: files/springervs.csl

language:
  lang: de
  ui:
    chapter_name: ""
  label:
    fig: 'Abbildung '
    tab: 'Tabelle '
    eq: 'Gleichung '
  section-title-appendices: "Anhang"

format:
  pdf:
    documentclass: scrreprt
    fontsize: 12pt
    classoption: twoside #bei digitalen Arbeiten oneside!
    geometry:
      - top=30mm
      - left=20mm
      - lmargin=30mm,
      - textwidth = 15.5cm,
      - textheight = 22.5cm
    keep-tex: true
    fontenc: T1
    template: files/LaTeX/quarto_template.tex
    fig-cap-location: top
    include-in-header:
      - text: |
      - file: files/LaTeX/macros.tex
    number-sections: true
    csquotes: true
    filters: [files/pandoc-quotes.lua]
    keep-md: false
        
  html:
    theme: cosmo
    filters: [files/pandoc-quotes.lua]
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
  docx: 
    toc: true
    toc-title: Inhalt
    number-sections: true
    number-depth: 3
    highlight-style: github
    reference-doc: files/template.docx
    
prefer-html: true

editor:
  render-on-save: false

header-includes:   
  - \usepackage{setspace}   #Package um Zeilenabstand zu wechseln
  - \onehalfspacing   #Zeilenabstand 1.5
  - \pagenumbering{gobble}  #Seitenzahlen Unterdrücken bis Kapitel 1