# Wenn Sie unten einen Teil haben, den Sie noch nicht verfasst haben, dann können Sie ihn mit # auskommentieren (nur nicht index.Rmd)

project:
  type: book
  output-dir: Bachelorarbeit # anpassen

Entwurfstatus: Entwurf 0.0 # regelmässig anpassen und am Ende auskommentieren (# an Anfangs)

institut: "Fachbereich Gesellschaftswissenschaften und Philosophie der Philipps-Universität Marburg"
papertype: "Bachelorarbeit im Fach Politikwissenschaft"
#AG: X
#Uebung: 0
#TutorIn: Vorname Nachname
#Modul: 'Bachelorarbeit'
#Semester: 'SoSe 24'
Gutachter:
  - type: Erstgutachterin
    name: Prof. Dr. Isabelle Borucki
    Email: borucki@uni-marburg.de
  - type: Zweitgutachterin
    name: Stine Ziegler
    Email: stine.ziegler@uni-marburg.de
Ort: Marburg
Jahr: 2024
Datum: "23.08.2024"

book:
  title: 'Polarisierung geschlechtergerechter Sprache' # eher knackig
  subtitle: 'Eine empirische Analyse anhand von Individualdaten, Bundestagsanträgen und Facebook-Posts' # bessere Beschreibung
  author:
  - given-names: Jakob
    surname: Krueger
    Email: Kruege4c@students.uni-marburg.de
    MatrikelNr: 3583647
    Studiengang: B.A. Politikwissenschaft
    Geburtsort: Halle (Saale)

  chapters:
    -  index.qmd
    -  01-Theorieteil.qmd
    -  02-Analyse-sui.qmd
    -  03-Analyse-bta.qmd
    -  04-Analyse-sm.qmd
    -  07-Schluss.qmd
  appendices:
    -  08-Anhang.qmd

  downloads: [pdf]
  output-file: Bachelorarbeit_Krueger_polges

bibliography: files/references.bib
cite-method: citeproc
csl: files/springervs.csl
# link-citations: true

language:
  lang: de
  ui:
    chapter_name: ""
  label:
    fig: 'Abbildung '
    tab: 'Tabelle '
    eq: 'Gleichung '
    #sec: 'Kapitel '
  section-title-appendices: "Anhang"
  crossref-sec-prefix: "Kapitel"
  crossref-fig-title: "Abbildung"
  crossref-tbl-title: "Tabelle"
  crossref-ch-prefix: "Kapitel"
  crossref-apx-prefix: "Anhang"

quot-lang: de

format:
  pdf:
    documentclass: scrreprt
    fontsize: 12pt
    classoption: twoside #bei digitalen Arbeiten oneside!
    geometry:
      - top=30mm
      - left=20mm
      - lmargin=30mm,
      - textwidth = 15.5cm,
      - textheight = 22.5cm
    keep-tex: true
    fontenc: T1
    template: files/LaTeX/quarto_template.tex
    fig-cap-location: top
    include-in-header:
      - text: |
      - file: files/LaTeX/macros.tex
    number-sections: true
    csquotes: true
    filters: [files/pandoc-quotes.lua]
    keep-md: false
        
  html:
    theme: cosmo
    filters: [files/pandoc-quotes.lua]
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
  docx: 
    toc: true
    toc-title: Inhalt
    number-sections: true
    number-depth: 3
    highlight-style: github
    reference-doc: files/template.docx
    
prefer-html: true

editor:
  render-on-save: false

header-includes:   
  - \usepackage{setspace}   #Package um Zeilenabstand zu wechseln
  - \onehalfspacing   #Zeilenabstand 1.5
  - \pagenumbering{gobble}  #Seitenzahlen Unterdrücken bis Kapitel 1