```{=tex}
\pagenumbering{arabic}
\setcounter{page}{1}
```
# Einleitung

```{r}
#| label: setup
#| include: false

source("_common.R")
```

Bei wenigen Themen geht das Diskussionsklima wie auf Knopfdruck so sehr durch die Decke wie beim "Gendern". Ein großer Treiber dieser Polarisierung sind die Medien und die Parteien – oft Akteure, die selbst von einer (behaupteten) Polarisierung profitieren. Dabei scheint es, dass vor allem die AfD das Thema immer wieder auf den "Markt" bringt, gern versehen mit der vorwurfsvollen Frage, ob wir denn nichts besseres zu tun hätten, als uns mit solchen Scheinproblemen auseinanderzusetzen. Doch stimmt das? Und wie ließe sich das quantifizieren? Auf diese Fragen gibt diese Arbeit eine Antwort. Untersucht wird anhand dreier Analyseebenen, ob die Ablehnung geschlechtergerechter Sprache von irgendwelchen sozialstrukturellen Merkmalen abhängig ist, welche Fraktionen geschlechtergerechte Sprache im Deutschen Bundestag thematisieren und ihr so einen parlamentarischen Raum geben und zuletzt welche Parteien geschlechtergerechte Sprache auf Facebook thematisieren und sich dabei populistischer Praktiken bedienen.

Die gesellschaftliche Relevanz dieses Themas spiegelt sich in zahlreichen Debatten auf Social Media oder im Alltag wieder, in denen mehr auf emotionaler denn rationaler Ebene gestritten wird. Aus politikwissenschaftlicher Sicht ist einerseits die Anwendung der neuen theoretischen Ansätze von Steffen Mau, Thomas Lux und Linus Westheuser [-@mau2024] interessant, aber auch die Erschließung von Bundestagsanträgen als Untersuchungsobjekt politikwissenschaftlicher Forschung. Letzteres verleiht dieser Studie einen explorativen Charakter.

Im ersten Teil der Arbeit wird ein theoretisches Fundament zur Bearbeitung der Fragestellungen gebaut. Im Fokus stehen geschlechtergerechte Sprache als wissenschaftliches wie auch gesellschaftliches Objekt, Bundestagsanträge, Populismus und zuletzt die Polarisierung der Gesellschaft und geschlechtergerechter Sprache. Im Anschluss an die Theorie werden die abgeleiteten Hypothesen empirisch gemessen – zuerst anhand von Individualdaten, dann von Bundestagsanträgen und schließlich von Facebook-Posts. Eine Zusammenfassung schließt die Arbeit mit einem Überblick über die roten Fäden dieser Studie sowie einem Ausblick.
